name: Terraform CI/CD

on:
  push:
    branches:
      - main

env:
  TF_PLUGIN_CACHE_DIR: ~/.terraform.d/plugin-cache

jobs:

  #################################################
  # Detect Changed Terraform Modules
  #################################################

  changes:

    runs-on: ubuntu-latest

    outputs:
      s3: ${{ steps.filter.outputs.s3 }}
      iam: ${{ steps.filter.outputs.iam }}
      sns: ${{ steps.filter.outputs.sns }}
      glue: ${{ steps.filter.outputs.glue }}
      lambda: ${{ steps.filter.outputs.lambda }}
      step_functions: ${{ steps.filter.outputs.step_functions }}

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Detect Changed Files
        uses: dorny/paths-filter@v3
        id: filter

        with:
          filters: |

            s3:
              - 'terraform/s3/**'

            iam:
              - 'terraform/iam/**'

            sns:
              - 'terraform/sns/**'

            glue:
              - 'terraform/glue/**'

            lambda:
              - 'terraform/lambda/**'

            step_functions:
              - 'terraform/step_functions/**'

  #################################################
  # S3 Infrastructure
  #################################################

  s3:

    if: needs.changes.outputs.s3 == 'true'

    needs:
      - changes

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./terraform/s3

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Cache Terraform Plugins
        uses: actions/cache@v4
        with:
          path: ~/.terraform.d/plugin-cache
          key: terraform-${{ runner.os }}-${{ hashFiles('**/.terraform.lock.hcl') }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve

  #################################################
  # IAM Infrastructure
  #################################################

  iam:

    if: needs.changes.outputs.iam == 'true'

    needs:
      - changes

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./terraform/iam

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Cache Terraform Plugins
        uses: actions/cache@v4
        with:
          path: ~/.terraform.d/plugin-cache
          key: terraform-${{ runner.os }}-${{ hashFiles('**/.terraform.lock.hcl') }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve

  #################################################
  # SNS Infrastructure
  #################################################

  sns:

    if: needs.changes.outputs.sns == 'true'

    needs:
      - changes

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./terraform/sns

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Cache Terraform Plugins
        uses: actions/cache@v4
        with:
          path: ~/.terraform.d/plugin-cache
          key: terraform-${{ runner.os }}-${{ hashFiles('**/.terraform.lock.hcl') }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve

  #################################################
  # Glue Infrastructure
  #################################################

  glue:

    if: needs.changes.outputs.glue == 'true'

    needs:
      - changes

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./terraform/glue

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Cache Terraform Plugins
        uses: actions/cache@v4
        with:
          path: ~/.terraform.d/plugin-cache
          key: terraform-${{ runner.os }}-${{ hashFiles('**/.terraform.lock.hcl') }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve

  #################################################
  # Lambda Infrastructure
  #################################################

  lambda:

    if: needs.changes.outputs.lambda == 'true'

    needs:
      - changes

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./terraform/lambda

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Cache Terraform Plugins
        uses: actions/cache@v4
        with:
          path: ~/.terraform.d/plugin-cache
          key: terraform-${{ runner.os }}-${{ hashFiles('**/.terraform.lock.hcl') }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var="youtube_api_key=${{ secrets.YOUTUBE_API_KEY }}"

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="youtube_api_key=${{ secrets.YOUTUBE_API_KEY }}"

  #################################################
  # Step Functions Infrastructure
  #################################################

  step_functions:

    if: needs.changes.outputs.step_functions == 'true'

    needs:
      - changes

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./terraform/step_functions

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Cache Terraform Plugins
        uses: actions/cache@v4
        with:
          path: ~/.terraform.d/plugin-cache
          key: terraform-${{ runner.os }}-${{ hashFiles('**/.terraform.lock.hcl') }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve