name: Terraform Deploy

on:
  push:
    branches:
      - main

env:
  TF_PLUGIN_CACHE_DIR: ~/.terraform.d/plugin-cache

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache Terraform Plugins
        uses: actions/cache@v4
        with:
          path: ~/.terraform.d/plugin-cache
          key: terraform-${{ runner.os }}-${{ hashFiles('**/.terraform.lock.hcl') }}

      - uses: hashicorp/setup-terraform@v3

      - name: Create Plugin Cache Directory
        run: mkdir -p ~/.terraform.d/plugin-cache

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Deploy s3
        working-directory: ./terraform/s3
        run: |
          terraform init
          terraform validate
          terraform apply -auto-approve

      - name: Deploy iam
        working-directory: ./terraform/iam
        run: |
          terraform init
          terraform validate
          terraform apply -auto-approve

      - name: Deploy sns
        working-directory: ./terraform/sns
        run: |
          terraform init
          terraform validate
          terraform apply -auto-approve

      - name: Deploy glue
        working-directory: ./terraform/glue
        run: |
          terraform init
          terraform validate
          terraform apply -auto-approve

      - name: Deploy lambda
        working-directory: ./terraform/lambda
        run: |
          terraform init
          terraform validate
          terraform apply -auto-approve -var="youtube_api_key=${{ secrets.YOUTUBE_API_KEY }}"

      - name: Deploy step_functions
        working-directory: ./terraform/step_functions
        run: |
          terraform init
          terraform validate
          terraform import aws_sfn_state_machine.yt_pipeline_state_machine arn:aws:states:ap-south-1:585008079281:stateMachine:yt-data-pipeline-orchestration-dev || true
          terraform apply -auto-approve

      - name: Deploy eventbridge
        working-directory: ./terraform/eventbridge
        run: |
          terraform init
          terraform validate
          terraform apply -auto-approve

      - name: Deploy monitoring
        working-directory: ./terraform/monitoring
        run: |
          terraform init
          terraform validate
          terraform apply -auto-approve

      - name: Deploy budget
        working-directory: ./terraform/budget
        run: |
          terraform init
          terraform validate
          terraform apply -auto-approve
